AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This cloudformation template is designed to create and manage the
  infrastructure of a static, S3 bucket hosted website.  Cloudfront is used to
  manage secure (https) connections and certificates, and could be used for
  network security or to limit access via WAF.  Eventually there will be an API
  gateway and at least one lambda in order to process the 'contact-me' page.
Resources:
  S3BucketForStaticSite:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      BucketName: '#{S3_BUCKET_NAME}#'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  PlayItForwardSACertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: 'playitforwardsa.org'
      SubjectAlternativeNames:
      - 'www.playitforwardsa.org'
      DomainValidationOptions:
      - DomainName: 'playitforwardsa.org'
        HostedZoneId: '#{AWS_HOSTED_ZONE_ID}#'
      - DomainName: 'www.playitforwardsa.org'
        HostedZoneId: '#{AWS_HOSTED_ZONE_ID}#'
      ValidationMethod: DNS
  StaticSiteCloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: '#{S3_BUCKET_NAME}#.s3-website-us-east-1.amazonaws.com'
            Id: myS3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          OriginRequestPolicyId: 59781a5b-3903-41f3-afcb-af62929ccde1
          TargetOriginId: myS3Origin
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: 'true'
        DefaultRootObject: index.html
        Aliases:
          - playitforwardsa.org
          - www.playitforwardsa.org
        ViewerCertificate:
          AcmCertificateArn: !Ref PlayItForwardSACertificate
          SslSupportMethod: sni-only
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  PlayItForwardSARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: '#{AWS_HOSTED_ZONE_ID}#'
      Name: playitforwardsa.org
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticSiteCloudfront.DomainName
        EvaluateTargetHealth: False
        HostedZoneId: Z2FDTNDATAQYW2
  WwwPlayItForwardSARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: '#{AWS_HOSTED_ZONE_ID}#'
      Name: www.playitforwardsa.org
      Type: A
      AliasTarget:
        DNSName: !GetAtt StaticSiteCloudfront.DomainName
        EvaluateTargetHealth: False
        HostedZoneId: Z2FDTNDATAQYW2


Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3BucketForStaticSite
      - WebsiteURL
    Description: URL for website hosted on S3
  CloudfrontURL:
    Value: !GetAtt
      - StaticSiteCloudfront
      - DomainName
    Description: URL for the Cloudfront Distribution
